// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function reducer(state, action) {
  if (action) {
    return {
            name: action._0
          };
  } else {
    return state;
  }
}

function Hello$NameInput(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(dispatch, /* ChangeName */{
                _0: value
              });
  };
  return React.createElement("input", {
              value: state.name,
              onChange: onChange
            });
}

var NameInput = {
  make: Hello$NameInput
};

function greeting(person) {
  if (typeof person === "number") {
    if (person !== 0) {
      return "Hello Director.";
    } else {
      return "Hey Professor!";
    }
  }
  var anyOtherName = person._0;
  switch (anyOtherName) {
    case "" :
        return "Is anyone here ?";
    case "Richard" :
        return "Still here Ricky?";
    default:
      return "Hey, " + anyOtherName + ".";
  }
}

var Demo = {
  greeting: greeting
};

function Hello$Greeting(Props) {
  var name = Props.name;
  return React.createElement("div", {
              className: "text-lg font-semibold border-yellow-400 border-8"
            }, greeting(/* Student */{
                  _0: name
                }));
}

var Greeting = {
  make: Hello$Greeting
};

function Hello$HelloWidget(Props) {
  var match = React.useReducer(reducer, {
        name: "Mr Hyde"
      });
  var state = match[0];
  return React.createElement("div", undefined, React.createElement("div", undefined, "What's your name hh?"), React.createElement(Hello$NameInput, {
                  state: state,
                  dispatch: match[1]
                }), React.createElement(Hello$Greeting, {
                  name: state.name
                }));
}

var HelloWidget = {
  make: Hello$HelloWidget
};

export {
  reducer ,
  NameInput ,
  Demo ,
  Greeting ,
  HelloWidget ,
  
}
/* react Not a pure module */
